python generate_plots_mg1_spot.py AO_vary_price_ratio_no_fail
python generate_plots_mg1_spot.py AO_vary_failure_rate
python generate_plots_mg1_spot.py OO_vary_price_ratio_no_fail
python generate_plots_mg1_spot.py OO_vary_failure_rate